---
# handlers file for ansible-aws-cloudwatch-client

- name: Setup awslogs with new config
  listen: "configure awslogs"
  command: python3 /tmp/awslogs-agent-setup.py --region eu-central-1 -c /tmp/awslogs.conf --non-interactive
  become: yes
